/*
 * This source file was generated by the Gradle 'init' task
 */
package net.tegulis.template

import com.google.common.truth.Truth.assertThat
import org.junit.jupiter.api.Test

class LibraryTest {
	@Test
	fun messageIsGenerated() {
		val inputName = "world"
		val expectedOutput = "Hello world!"
		val actualOutput = Library.generateMessage(inputName)
		assertThat(actualOutput).isEqualTo(expectedOutput)
	}
}
